<?php
/**
 * Implementation of hook_permission().
 * Create 2 perms for display advice message and configure advice message
 */

function fb_fan_permission() {
  return array(
    'administer fb_fan settings' => array(
      'title' => t('administer fb_fan settings'), 
    ),	
  );
}

/**
 * Implementation of hook_menu()
 * Create admin page in order to change advice message
 */ 
function fb_fan_menu() {
  
  $items = array();

  $items['admin/settings/fb_fan'] = array(
	'title' => t('Facebook Fan'),
	'description' => t('Requirements to implement a Facebook fan box'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fb_fan_settings'),
    'access arguments' => array('administer fb_fan settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}


/**
* Implementation of hook settings
*/
function fb_fan_settings() {
	$form['fb_fan_general_settings'] = array(
		'#title' => t('General Settings'),
		'#type' => "fieldset",
		'#collapsible' => FALSE,
	);
	$form['fb_fan_general_settings']['api_key'] = array(
		'#title' => t('API Key'),
		'#type' => "textfield",
		'#size' => 45,
		'#maxlength' => 50,
		'#required' => TRUE,
		'#description' => t('Ex. 6ef2b05cd423f7d1e252f6be07de8557'),
		'#default_value' => variable_get('api_key',''),
	);
	$form['fb_fan_general_settings']['profile_id'] = array(
		'#title' => t('Profile ID'),
		'#type' => "textfield",
		'#size' => 45,
		'#maxlength' => 50,
		'#required' => TRUE,
		'#description' => t('Ex. 374542984235'),
		'#default_value' => variable_get('profile_id',''),
	);
	$form['fb_fan_general_settings']['connections'] = array(
		'#title' => t('Connection Amount'),
		'#type' => "textfield",
		'#size' => 45,
		'#maxlength' => 50,
		'#required' => TRUE,
		'#description' => t('Number of fans to display'),
		'#default_value' => variable_get('connections',''),
	);
	$form['fb_fan_general_settings']['width'] = array(
		'#title' => t('Width'),
		'#type' => "textfield",
		'#size' => 45,
		'#maxlength' => 50,
		'#required' => TRUE,
		'#description' => t('Width of the fan box'),
		'#default_value' => variable_get('width',''),
	);
	$form['fb_fan_general_settings']['height'] = array(
		'#title' => t('Height'),
		'#type' => "textfield",
		'#size' => 45,
		'#maxlength' => 50,
		'#required' => TRUE,
		'#description' => t('Height of the fan box'),
		'#default_value' => variable_get('height',''),
	);
	$form['fb_fan_general_settings']['stream'] = array(
		'#title' => t('Stream'),
		'#type' => "checkbox",
		'#description' => t('Show postings from the Facebook page'),
		'#default_value' => variable_get('stream','1'),
	);
	$form['fb_fan_general_settings']['logo'] = array(
		'#title' => t('Facebook Logo'),
		'#type' => "checkbox",
		'#description' => t('Show the Facebook logo'),
		'#default_value' => variable_get('logo','1'),
	); 
	$form['fb_fan_general_settings']['header'] = array(
		'#title' => t('Facebook Header'),
		'#type' => "checkbox",
		'#description' => t('Show the Facebook Header'),
		'#default_value' => variable_get('header','1'),
	); 	
	return system_settings_form($form);
}

/**
 * Implementation of hook_block_info().
 */
function fb_fan_block_info() {
  $blocks = array();
    $blocks['facebook_fan'] = array(
      'info' => t('Facebook Fan'),
      'cache' => DRUPAL_NO_CACHE,
    );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function fb_fan_block_view($block_name = '') {
  if ($block_name = 'facebook_fan') {
    // $delta is validated, the block can be displayed.
	//Build Block content
	
	 $css = 'http://' . $_SERVER['HTTP_HOST'] . '/' . path_to_theme(). '/fb_fan.css?' . rand(1, 1000000);
	 $api_key = variable_get('api_key', FALSE);
	 $profile_id = variable_get('profile_id', FALSE);
	 $stream = variable_get('stream', 1);
	 $connection = variable_get('connections', FALSE);
	 $logo = variable_get('logo', 1);
	 $header = variable_get('header', 1);
	 $width = variable_get('width', FALSE);
	 $height = variable_get('height', FALSE); 	
	
	 $content = '';
	 $content .= '<div id="fb-root"></div>' ;
	 $content .= '<script src="http://connect.facebook.net/fr_FR/all.js#xfbml=1"></script>' ;
	 $content .= '<script type="text/javascript">FB.init("'. $api_key . '");</script>';
	 $content .= '<fb:fan profile_id="' . $profile_id .'"  width="'. $width . '" height="' . $height .'" show_faces="true"  stream="' . $stream . '" header="' .$header . '" connections= "18" css="' . $css . '" logobar="'. $logo . '"></fb:fan>';	
    
	$block = array(
      'subject' => t('Facebook Fan'),	  
      'content' => $content,
    );
    return $block;
  }
}

 

